unit Model.Artista;

interface

uses
  Spring,
  Spring.Persistence.Mapping.Attributes;

type

  [ Entity ]
  [ Table('Artist') ]
  TArtista = class
  private
    [ AutoGenerated ]
    FArtistId: integer;
    FName    : string;

    procedure SetArtistId(const Value: integer);
    procedure SetName(const Value: string);
  public
    [ Column('ArtistId', [ cpPrimaryKey, cpDontInsert ], 0, 'ArtistId') ]
    property ArtistId: integer read FArtistId write SetArtistId;
    [ Column('Name', [ ], 120, 'Name') ]
    property Name: string read FName write SetName;
  end;

implementation

  { TArtista }

procedure TArtista.SetArtistId(const Value: integer);
begin
  FArtistId := Value;
end;

procedure TArtista.SetName(const Value: string);
begin
  FName := Value;
end;

end.
